# 45장. 🤙 프로미스

## 📌 45.1 비동기 처리를 위한 콜백 패턴의 단점

자바스크립트는 비동기 처리를 위해 콜백 함수를 사용했으나, 다음과 같은 문제점이 있다.

- 콜백 헬로 인해 가독성이 나쁨
- 비동기 처리 중 발생한 에러의 처리가 어려움
- 여러 개의 비동기 처리를 한번에 처리하는 데 한계가 있음

### 45.1.1 콜백 헬

비동기 함수는 비동기 처리 결과를 외부에 반환할 수 없고, 상위 스코프 변수에 할당할 수도 없다.

- 따라서 비동기 함수의 처리 결과(서버 응답, 에러 처리)에 대한 후속 처리는 비동기 함수 내부에서 수행해야함
- 이 때 비동기 함수를 범용적으로 사용하기 위해 **비동기 함수에 비동기 처리 결과에 대한 후속 처리를 수행**하는 `콜백 함수`를 전달
    - 필요에 따라 비동기 처리가 성공하면 호출될 콜백 함수와 처리가 실패하면 호출될 콜백 함수를 전달할 수 있다.


<b>콜백 헬(callback hell)</b>이란 위처럼 비동기 함수의 처리 결과에 대한 후속 처리를 진행하기 위한 콜백 함수를 사용하는데, 비동기 함수가 비동기 처리 결과를 가지고 또다시 비동기 함수를 호출해야 한다면 콜백 함수가 중첩되어 호출되고 이로 인해 복잡도가 높아지는 현상을 말한다.

```jsx
// GET 요청을 위한 비동기 함수
const get = (url, callback) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 서버의 응답을 콜백 함수에 전달하면서 호출하여 응답에 대한 후속 처리를 한다.
      callback(JSON.parse(xhr.response));
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

const url = 'https://jsonplaceholder.typicode.com';

// id가 1인 post의 userId를 취득
get(`${url}/posts/1`, ({ userId }) => {
  console.log(userId); // 1
  // post의 userId를 사용하여 user 정보를 취득
  get(`${url}/users/${userId}`, userInfo => {
    console.log(userInfo); // {id: 1, name: "Leanne Graham", username: "Bret",...}
  });
});

// 콜백 헬
get('/step1', a => {
  get(`/step2/${a}`, b => {
    get(`/step3/${b}`, c => {
      get(`/step4/${c}`, d => {
        console.log(d);
      });
    });
  });
});
```

<br>

### 45.1.2 에러 처리의 한계

```jsx
try {
  setTimeout(() => { throw new Error('Error!'); }, 1000);
} catch (e) {
  // 에러를 캐치하지 못한다
  console.error('캐치한 에러', e);
}
```

위 예제에서는 비동기 함수 setTimeout의 콜백 함수에서 발생하는 에러가 catch 블록에서 캐치되지 않는다.

1. **비동기 함수 `setTimeout`의 처리**
    
    `setTimeout` 함수는 호출될 때 즉시 실행 컨텍스트를 생성하고 콜 스택에 푸시된다. 그러나 `setTimeout` 자체는 비동기적으로 실행되므로, 함수의 실행이 완료되면 곧바로 콜 스택에서 제거된다. 이 때 `setTimeout`의 콜백 함수는 아직 실행되지 않는다.
    
2. **콜백 함수의 실행**
    
    설정된 시간이 지난 후, `setTimeout`의 콜백 함수는 태스크 큐에 푸시된다. 이벤트 루프가 콜 스택이 비어 있을 때 태스크 큐에서 콜백 함수를 콜 스택으로 이동시켜 실행한다.
    
3. **에러 전파의 방향**
    
    JavaScript에서 에러는 호출자(caller) 방향, 즉 콜 스택에서 아래쪽으로 전파된다. 그러나 `setTimeout`의 콜백 함수는 이미 `setTimeout` 함수가 콜 스택에서 제거된 후에 실행되기 때문에, 콜백 함수 내에서 발생하는 에러는 `setTimeout` 함수나 그 주변의 코드로 전파되지 않는다. 따라서 `try...catch` 블록으로 캐치할 수 없다.
    
4. **콜백 함수를 호출한 실행 컨텍스트**
    
    `setTimeout`의 콜백 함수를 호출하는 것은 이벤트 루프다. 콜백 함수는 `setTimeout` 함수가 아니라 이벤트 루프에 의해 실행 컨텍스트에 푸시되어 실행된다. 이 과정은 기존 콜 스택의 실행 컨텍스트와 독립적이기 때문에, 콜백 내에서 발생하는 에러는 이전 실행 컨텍스트나 `try...catch` 블록과 관련이 없다.
    

위처럼 비동기 처리를 위한 콜백 패턴은 콜백 헬로 인한 가독성 저하, 에러 처리의 한계라는 문제가 있다. 이를 위해 ES6에서 프로미스(Promise)가 도입되었다.

<br>
<br>

## 📌 45.2 프로미스의 생성

`Promise` 생성자 함수를 `new` 연산자와 함께 호출하면 Promise 객체를 생성한다.

- Promise는 호스트 객체가 아닌 ECMAScript 사양에 정의된 표준 빌트인 객체
- `Promise` 생성자 함수는 비동기 처리를 수행할 콜백 함수를 인수로 전달받는데, 이 콜백 함수는 `resolve`와 `reject` 함수를 인수로 전달받는다.

```jsx
// 프로미스 생성
const promise = new Promise((resolve, reject) => {
  // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행한다.
  if (/* 비동기 처리 성공 */) {
    resolve('result');
  } else { /* 비동기 처리 실패 */
    reject('failure reason');
  }
});
```

| 프로미스의 상태 정보 | 의미 | 상태 변경 조건 |
| --- | --- | --- |
| pending | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
| fulfilled | 비동기 처리 성공 (처리 결과 값: 1) | resolve 함수 호출 |
| rejected | 비동기 처리가 수행된 상태 (처리 결과 값: Error 객체) | reject 함수 호출 |
- 비동기 처리 성공 : `resolve` 함수 호출 → 프로미스를 `fulfilled` 상태로 변경
- 비동기 처리 실패 : `rejected` 함수 호출 → 프로미스를 `rejected` 상태로 변경

프로미스는 비동기 처리 상태`[[PromiseStatus]]`와 더불어 비동기 처리 결과[`[PromiseValue]]`도 상태로 갖는다.

즉, **프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체**다.

<br>
<br>

## 📌 45.3 프로미스의 후속 처리 메서드

- 프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출됨
- **후속 처리 메서드는 언제나 프로미스를 반환함**

### Promise.prototype.then

- then 메서드는 두 개의 콜백 함수를 인수로 전달받음
    - 첫 번째 콜백 함수는 비동기 처리 성공 시 호출되는 성공 처리 콜백 함수, 두 번째 콜백 함수는 처리 실패 시 호출되는 실패 처리 콜백 함수
    - 성공(fulfilled) 및 실패(rejected) 케이스 모두 처리할 수 있음
    - 두 번째 콜백 함수는 `catch`와 동일한 역할

```jsx
// fulfilled
new Promise(resolve => resolve('fulfilled'))
  .then(v => console.log(v), e => console.error(e)); // fulfilled

// rejected
new Promise((_, reject) => reject(new Error('rejected')))
  .then(v => console.log(v), e => console.error(e)); // Error: rejected
```

### Promise.prototype.catch

- catch 메서드는 한 개의 콜백 함수를 인수로 전달받음
    - 프로미스가 rejected 상태인 경우에만 호출됨

### Promise.prototype.finally

- finally 메서드는 한 개의 콜백 함수를 인수로 전달받음
    - 프로미스의 상태가 성공(fulfilled)인지 실패(rejected)인지에 관계없이 무조건 한 번 호출됨
- finally 메서드는 프로미스의 상태와 상관없이 공통적으로 수행해야 할 처리 내용이 있을 때 유용

<br>
<br>

## 📌 45.4 프로미스의 에러 처리

비동기 처리 결과에 대한 후속 처리는 프로미스가 제공하는 후속 처리 메서드 then, catch, finally를 사용하여 수행한다.

프로미스의 에러 처리는 `then 메서드의 두 번째 콜백 함수` 또는 `catch 메서드`를 사용해 처리할 수 있다.

- 모든 then 메서드를 호출한 이후 catch 메서드를 호출하면 비동기 처리에서 발생한 에러와 then 메서드 내부에서 발생한 에러까지 캐치할 수 있음
- then 메서드에 두 번째 콜백 함수를 전달하는 것보다 catch 메서드를 사용하는 것이 가독성이 좋고 명확

따라서 에러 처리는 then 메서드에서 하기보다 **catch 메서드에서 하는 것이 권장**된다.

<br>
<br>

## 📌 45.5 프로미스 체이닝

then, catch, finally 후속 처리 메서드는 언제나 프로미스를 반환하므로 연속적으로 호출할 수 있게 되는데, 이것을 프로미스 체이닝(Promise chaining)이라고 한다.

ES8에서 도입된 `async/await`를 사용하면 프로미스의 후속 처리 메서드없이 마치 동기 처리처럼 프로미스가 처리 결과를 반환하도록 구현할 수 있다.

<br>
<br>

## 📌 45.6 프로미스의 정적 메서드

### Promise.resolve / Promise.reject

- 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용
- Promise.resolve 메서드는 인수로 전달받은 값을 resolve하는 프로미스를, Promse.reject 메서드는 인수로 전달받은 값을 reject하는 프로미스를 생성

### Promise.all

- 여러 개의 비동기 처리를 모두 병렬처리 할 때 사용
- 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받음
    
    > 이터러블 : JavaScript에서 반복 가능한 객체, 즉 반복자(iterator)를 통해 그 요소들을 한 번에 하나씩 순회할 수 있는 객체를 의미
    > 
- 인수로 전달받은 배열의 프로미스가 하나라도 rejected 상태가 되면 나머지 프로미스와 관계없이 즉시 종료하고 실패를 반환 (Fail Fast)

### Promise.race

- 여러 개의 프로미스 중 가장 먼저 완료되는(fulfilled 되거나 rejected되는) 프로미스의 결과 또는 오류를 반환 (race 중 1등만 뽑겠다)
- 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받음

### Promise.allSettled

- 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받고, 전달받은 프로미스가 모두 settled 상태가 되면 처리 결과를 배열로 반환
    - settled 상태 : 비동기 처리가 수행된 상태(fulfilled 또는 rejected 상태)
- Promise.allSettled 메서드가 반환한 배열에는 fulfilled, rejected 상태 모두에 대한 프로미스의 처리 결과들이 담겨있음
    - 하나라도 rejected가 되면 즉시 종료되고 실패 결과를 반환하는 Promise.all과 차이

<br>
<br>

## 📌 45.7 마이크로태스크 큐

- 마이크로태스크 큐에는 **프로미스 후속 처리 메서드의 콜백 함수**가 저장됨
    - 그 외 비동기 함수의 콜백 함수나 이벤트 핸들러는 태스크 큐에 저장
- 마이크로태스크 큐는 태스크 큐보다 **우선순위가 높음**
    - **즉, 언제나 프로미스가 다른 비동기 통신보다 우선한다.**

```jsx
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));

// 출력 순서 - 2, 3, 1
```

<br>
<br>

## 📌 45.8 fetch

fetch 함수는 XMLHttpRequest 객체와 마찬가지로 HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API다.

- fetch 함수는 XMLHttpRequest보다 사용법이 간단하고 프로미스를 지원하므로 비동기 처리를 위한 콜백 패턴의 단점에서 자유로움
- fetch 함수에는 HTTP 요청을 전송할 URL과 HTTP 요청 메서드, HTTP 요청 헤더, 페이로드 등을 설정한 객체를 전달
    
    ```jsx
    const promise = fetch(url, [, options]
    ```
    
- fetch 함수는 **HTTP 응답을 나타내는 Respose 객체를 래핑한 Promise 객체를 반환**

<br>    

### fetch 함수가 불편한 이유?

- 여전히 fetch 함수가 불편한 이유는 `Response`를 역직렬화를 해주어야 하기 때문
    - axios와 같은 라이브러리를 사용하면 바로 자바스크립트 객체 `Response`로 받아볼 수 있는 것과 대비
    
    ```jsx
    fetch('https://jsonplaceholder.typicode.com/todos/1')
      // response는 HTTP 응답을 나타내는 Response 객체이다.
      // json 메서드를 사용하여 Response 객체에서 HTTP 응답 몸체를 취득하여 역직렬화한다.
      .then(response => response.json())
      // json은 역직렬화된 HTTP 응답 몸체이다.
      .then(json => console.log(json));
      // {userId: 1, id: 1, title: "delectus aut autem", completed: false}
    ```
    

- fetch 함수가 반환하는 프로미스는 기본적으로 404나 500과 같은 HTTP 에러가 발생해도 에러를 reject하지 않고 불리언 타입의 ok 상태를 false로 설정한 `Response` 객체를 resolve함
    - 오프라인 등의 네트워크 장애나 CORS 에러에 의해 요청이 완료되지 못한 경우에만 프로미스를 reject함
    
    ```jsx
    const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';
    
    // 부적절한 URL이 지정되었기 때문에 404 Not Found 에러가 발생한다.
    fetch(wrongUrl)
      // response는 HTTP 응답을 나타내는 Response 객체다.
      .then(response => {
        if (!response.ok) throw new Error(response.statusText);
        return response.json();
      })
      .then(todo => console.log(todo))
      .catch(err => console.error(err));
    ```
    
    - 참고로 axios는 모든 HTTP 에러를 reject하는 프로미스를 반환하므로 모든 에러를 catch에서 처리할 수 있어 편리

<br>
<br>